### ISSUE TITLE
v1.2 Use Github Project Management

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T16-B2/main#33]
**Tasks we have to do from v1.2 onwards:**

> 🚩To consider the milestone as 'reached', you should have the following done before the tutorial begins. Missed milestones will count against the 'project management' component of your final grade:

- [x] A working product tagged with the correct tag (e.g. v1.2) and pushed to the main repo.

- [x] All tests passing on Travis.

- [x] Milestone updated to match the product.

- [x] Milestone closed. All issues assigned to that milestone should be closed too.
Doing a 'release' on GitHub is optional v1.2 but compulsory from v1.3.

**Each member is expected to contribute some code to each weekly milestone; only merged code is considered as contributions.**

> 🚩If you miss more than two weekly milestones, you will start losing marks.

If an enhancement is too big to complete in one week, here are some options:

- [Preferred] Deliver it in smaller incremental steps e.g. deliver a basic version of the enhancement first.

- Do a different, smaller, enhancement for the current week while working on a bigger enhancement to deliver in a future week.

- Choose not contribute to the weekly milestone. This should be fine as long as you don't miss more than two milestones.
