### ISSUE TITLE
v1.2 Features Todo List

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T16-B2/main#34]
🚩Features to be completed by Thursday Before Tutorial

Grading: Criteria to consider this milestone as reached

- [x] Add fields Class, Grade - Jiachao

- [x] Reformat phone numbers (Student number & Teacher number) - Lenald

- [x] Sorting by different parameters; name, class,(add drop-down button) - Celine

- [x] Add Remarks field (Same as the sample one) - Jonathan

- [x] A new version tagged v1.2 is in your repo. - All

The version v1.2 is step towards v2.0 (but it does not matter how big a step it is)
